#!/usr/bin/env bash
set -euo pipefail

node - <<'NODE'
const fs = require('fs');
const vm = require('vm');
const keyboardStatus = { textContent: '' };
const disclosureSummary = { textContent: 'Keyboard guide', focusCalls: 0, focus() { this.focusCalls += 1; } };
const disclosure = { open: true, querySelector(selector) { return selector === 'summary' ? disclosureSummary : null; } };
const disclosureTarget = { closest(selector) { return selector === 'details[open]' ? disclosure : null; } };
const catalogResultCount = { textContent: '', attributes: {}, setAttribute(name, value) { this.attributes[name] = value; } };
const catalogLiveStatus = { textContent: '' };
const elements = new Map();
const makeSelect = (options = []) => ({ options, selectedOptions: [], appendChild(option) { this.options.push(option); } });
const searchInput = { value: '' };
const activeFilters = { hidden: true, innerHTML: '', attributes: {}, setAttribute(name, value) { this.attributes[name] = value; } };
const filterSelect = makeSelect();
const filterPlace = makeSelect();
const filterEra = makeSelect();
const filterAxis = makeSelect();
const sortSelect = makeSelect([{ value: 'index' }]);
const filterStatus = makeSelect([
  { value: 'all', textContent: 'All statuses' },
  { value: 'schematic', textContent: 'Schematic' },
  { value: 'measured', textContent: 'Measured' }
]);
const drawingState = { textContent: '' };
const zoomReadout = { textContent: '' };
const zoomReset = { textContent: '', title: '' };
const zoomOut = { disabled: false, title: '', setAttribute() {} };
const zoomIn = { disabled: false, title: '', setAttribute() {} };
const navLinks = ['atlas', 'compare', 'method'].map((view) => ({
  dataset: { view },
  setAttribute(name, value) { this[name] = value; }
}));
const layerButtons = ['all', 'envelope', 'rhythm', 'axis', 'measure'].map((layer) => ({
  dataset: { layer },
  setAttribute(name, value) { this[name] = value; },
  classList: { toggle() {} },
  title: ''
}));
const methodLink = { setAttribute(name, value) { this[name] = value; } };
const context = {
  URL,
  window: {
    location: { href: 'https://example.test/atlas/?q=central%20plan#atlas/basilica/plan/exterior/all' }
  },
  document: {
    body: { classList: { remove() {} } },
    createElement() { return {}; },
    querySelector(selector) { return selector === '#keyboardStatus' ? keyboardStatus : elements.get(selector) || null; },
    querySelectorAll(selector) { return selector === '[data-view]' ? navLinks : selector === '[data-layer]' ? layerButtons : []; }
  }
};
vm.runInNewContext(fs.readFileSync('data/geometry.js', 'utf8'), context);
const firstStudy = context.window.CHURCH_GEOMETRY[0];
const secondStudy = context.window.CHURCH_GEOMETRY[1];
const lastStudy = context.window.CHURCH_GEOMETRY[context.window.CHURCH_GEOMETRY.length - 1];
const studyCount = context.window.CHURCH_GEOMETRY.length;
const studyCountLabel = String(studyCount).padStart(2, '0');
const schematicCount = context.window.CHURCH_GEOMETRY.filter((study) => study.status === 'schematic').length;
const gothicCount = context.window.CHURCH_GEOMETRY.filter((study) => study.typology === 'Gothic').length;
const sixthCenturyCount = context.window.CHURCH_GEOMETRY.filter((study) => study.era === '6th century').length;
const longitudinalCount = context.window.CHURCH_GEOMETRY.filter((study) => study.axis === 'Longitudinal').length;
const radialCount = context.window.CHURCH_GEOMETRY.filter((study) => study.axis === 'Radial').length;
const studyIdentity = (study) => `Study ${study.index}, ${study.shortName || study.name}`;
elements.set('#searchInput', searchInput);
elements.set('#activeFilters', activeFilters);
elements.set('#filterSelect', filterSelect);
elements.set('#filterPlace', filterPlace);
elements.set('#filterEra', filterEra);
elements.set('#filterAxis', filterAxis);
elements.set('#filterStatus', filterStatus);
elements.set('#sortSelect', sortSelect);
elements.set('#drawingState', drawingState);
elements.set('#zoomReadout', zoomReadout);
elements.set('#zoomReset', zoomReset);
elements.set('#zoomOut', zoomOut);
elements.set('#zoomIn', zoomIn);
elements.set('#catalogResultCount', catalogResultCount);
elements.set('#catalogLiveStatus', catalogLiveStatus);
elements.set('[data-method-link]', methodLink);
const app = fs.readFileSync('app.js', 'utf8').replace('  init();\n})();', '  window.__atlasTest = { state, routeHash, navigationUrl, atlasStudyNavigationUrl, catalogViewRouteUrl, studyRouteUrl, studyRoutePath, methodNavigationUrl, comparisonNavigationUrl, viewNavigationUrl, updateViewNavigationLinks, parseRoute, handleKeyboard, handleDisclosureKeydown, handleViewNavigation, renderStudyNav, renderControls, drawPlan, drawElevation, drawSection, studySearchText, highlightSearchText, searchMatchContext, catalogStudyAriaLabel, populateFilter, renderCatalogFilterOptions, renderActiveFilters, visibleStudies, catalogScopeLabel, catalogStatusGuidanceText, renderCatalogResultCount, syncCatalogFromUrl, normalizeCatalogQuery, zoomDeltaForKey };\n})();');
vm.runInNewContext(app, context);
const { state, routeHash, navigationUrl, atlasStudyNavigationUrl, catalogViewRouteUrl, studyRouteUrl, studyRoutePath, methodNavigationUrl, comparisonNavigationUrl, viewNavigationUrl, updateViewNavigationLinks, parseRoute, handleKeyboard, handleDisclosureKeydown, handleViewNavigation, renderStudyNav, renderControls, drawPlan, drawElevation, drawSection, studySearchText, highlightSearchText, searchMatchContext, catalogStudyAriaLabel, populateFilter, renderCatalogFilterOptions, renderActiveFilters, visibleStudies, catalogScopeLabel, catalogStatusGuidanceText, renderCatalogResultCount, syncCatalogFromUrl, normalizeCatalogQuery, zoomDeltaForKey } = context.window.__atlasTest;
const records = context.window.CHURCH_GEOMETRY;
const totalCount = records.length;
const padCount = (count) => String(count).padStart(2, '0');
const schema = context.window.CHURCH_GEOMETRY_SCHEMA;
const statusValues = schema.statusValues;
const statusLabel = (value) => String(value).charAt(0).toUpperCase() + String(value).slice(1);
const statusCount = (value, scope = records) => scope.filter((study) => study.status === value).length;
const axisLabel = (value) => /axis$/i.test(value) ? value : `${value} axis`;
const countBy = (key, value) => records.filter((study) => study[key] === value).length;
const uniqueStudyFor = (key) => records.find((study) => countBy(key, study[key]) === 1) || records[0];
const uniqueEraStudy = uniqueStudyFor('era');
const uniqueAxisStudy = uniqueStudyFor('axis');
const multiTermQuery = `${secondStudy.typology.toLowerCase()} ${secondStudy.place.split(',')[0].trim().toLowerCase()}`;
const identityLabel = (study) => `Study ${study.index}, ${study.shortName || study.name}`;
const scopeCountText = (count) => `${padCount(count)} of ${padCount(totalCount)} studies`;
const statusSummary = (scope) => statusValues.map((value) => `${statusCount(value, scope)} ${statusLabel(value).toLowerCase()}`).join(' · ');
populateFilter();
renderControls();
const disclosureEvent = { key: 'Escape', target: disclosureTarget, prevented: false, preventDefault() { this.prevented = true; } };
handleDisclosureKeydown(disclosureEvent);
if (!disclosureEvent.prevented || disclosure.open || disclosureSummary.focusCalls !== 1 || keyboardStatus.textContent !== 'Keyboard guide closed.') throw new Error('Escape did not close the open disclosure, restore summary focus, and announce the handoff');
renderCatalogResultCount(totalCount);
if (catalogResultCount.textContent !== scopeCountText(totalCount) || catalogResultCount.attributes['aria-label'] !== `${scopeCountText(totalCount)}; the full collection.` || catalogLiveStatus.textContent !== '') throw new Error('Initial catalog result announcement was not concise and scoped');
state.query = 'gothic';
state.filterAxis = 'Longitudinal';
state.sort = 'name';
state.sortDirection = 'asc';
const axisFilteredCount = visibleStudies().length;
renderCatalogResultCount(axisFilteredCount);
const axisFilteredScope = catalogScopeLabel();
if (catalogResultCount.attributes['aria-label'] !== `${scopeCountText(axisFilteredCount)}; ${axisFilteredScope}.` || catalogLiveStatus.textContent !== `Catalog updated: ${axisFilteredScope}.`) throw new Error('Catalog scope announcement did not include query, filter, sort, and accessible result context');
if (normalizeCatalogQuery(`  ${secondStudy.typology}   ${secondStudy.place.split(',')[0]}  `) !== multiTermQuery) throw new Error('Catalog query normalization did not collapse repeated whitespace');
state.query = multiTermQuery;
const multiTermScopedCount = visibleStudies().length;
renderCatalogResultCount(multiTermScopedCount);
const multiTermScope = catalogScopeLabel();
if (catalogLiveStatus.textContent !== `Catalog updated: ${multiTermScope}.`) throw new Error('Catalog scope announcement did not update when the result count stayed the same');
state.query = '';
state.filterAxis = 'all';
state.sort = 'index';
renderCatalogResultCount(totalCount);
if (catalogLiveStatus.textContent !== 'Catalog updated: the full collection.') throw new Error('Catalog scope announcement did not describe the restored full collection');
state.filterStatus = 'schematic';
const schematicScopeCount = visibleStudies().length;
renderCatalogResultCount(schematicScopeCount);
const schematicScope = catalogScopeLabel();
if (catalogLiveStatus.textContent !== `Catalog updated: ${schematicScope}. Data status filter: ${statusLabel('schematic')}. ${schema.statusDefinitions.schematic}`) throw new Error('Catalog status filter announcement did not include the schema-backed definition');
state.filterStatus = 'all';
renderCatalogResultCount(totalCount);
if (catalogLiveStatus.textContent !== 'Catalog updated: the full collection. Data status filter cleared.') throw new Error('Catalog status filter announcement did not describe a cleared filter');
state.filter = secondStudy.typology;
state.filterPlace = secondStudy.place;
state.filterEra = secondStudy.era;
state.filterAxis = secondStudy.axis;
state.filterStatus = 'schematic';
state.sort = 'name';
const activeScope = catalogScopeLabel();
if (activeScope !== `typology: ${secondStudy.typology}, location: ${secondStudy.place}, era: ${secondStudy.era}, axis: ${axisLabel(secondStudy.axis)}, data status: schematic records, sorted by name (A–Z)`) throw new Error(`Catalog scope labels were not self-describing: ${activeScope}`);
filterSelect.selectedOptions = [{ textContent: `${secondStudy.typology} · ${countBy('typology', secondStudy.typology)}` }];
filterPlace.selectedOptions = [{ textContent: `${secondStudy.place} · ${countBy('place', secondStudy.place)}` }];
filterEra.selectedOptions = [{ textContent: `${secondStudy.era} · ${countBy('era', secondStudy.era)}` }];
filterAxis.selectedOptions = [{ textContent: `${axisLabel(secondStudy.axis)} · ${countBy('axis', secondStudy.axis)}` }];
filterStatus.selectedOptions = [{ textContent: `Schematic · ${schematicCount}` }];
sortSelect.selectedOptions = [{ textContent: 'Name · A–Z' }];
renderActiveFilters();
for (const label of [`Typology: ${secondStudy.typology} · ${countBy('typology', secondStudy.typology)}`, `Location: ${secondStudy.place} · ${countBy('place', secondStudy.place)}`, `Era: ${secondStudy.era} · ${countBy('era', secondStudy.era)}`, `Axis: ${axisLabel(secondStudy.axis)} · ${countBy('axis', secondStudy.axis)}`, `Data status: Schematic · ${schematicCount}`, 'Sort: Name · A–Z']) {
  if (!activeFilters.innerHTML.includes(label)) throw new Error(`Active filter chip lost its context label: ${label}`);
}
if (activeFilters.hidden || activeFilters.attributes['aria-label'] !== '6 active catalog settings' || !activeFilters.innerHTML.includes(`aria-label="Clear Data status: Schematic · ${schematicCount}"`)) throw new Error('Active catalog settings did not expose its count and a descriptive data-status clearing action');
state.sortDirection = 'desc';
sortSelect.selectedOptions = [{ textContent: 'Name · Z–A' }];
renderActiveFilters();
if (!activeFilters.innerHTML.includes('Sort: Name · Z–A') || !activeFilters.innerHTML.includes('aria-label="Clear all active catalog settings"')) throw new Error('Active catalog settings did not preserve the reversed sort direction or accurately describe its clear action');
state.filter = 'all';
state.filterPlace = 'all';
state.filterEra = 'all';
state.filterAxis = 'all';
state.filterStatus = 'all';
state.sort = 'index';
renderActiveFilters();
if (!activeFilters.hidden || activeFilters.attributes['aria-label'] !== 'Active catalog settings') throw new Error('Active catalog settings did not reset its accessible name after clearing the view');
if (drawingState.textContent !== 'Outside · Plan · all geometry · 100% zoom') throw new Error(`Initial drawing context did not render: ${drawingState.textContent}`);
const axisLayer = layerButtons.find((button) => button.dataset.layer === 'axis');
if (!axisLayer || axisLayer['aria-label'] !== 'Axis focus: Directional lines and central geometric guides.' || axisLayer.title !== axisLayer['aria-label']) throw new Error('Drawing layer controls did not expose their accessible definitions');
state.surface = 'interior';
state.mode = 'section';
state.layer = 'axis';
state.zoom = 1.3;
renderControls();
if (drawingState.textContent !== 'Inside · Section · axis focus · 130% zoom') throw new Error(`Drawing context did not follow the active view: ${drawingState.textContent}`);
if (zoomOut.title !== 'Zoom out' || zoomReset.title !== 'Reset zoom to 100%' || zoomIn.title !== 'Zoom in') throw new Error('Zoom controls did not expose synchronized tooltips');
state.zoom = 0.7;
renderControls();
if (!zoomOut.disabled || zoomOut.title !== 'Zoom out (minimum 70%)') throw new Error('Minimum zoom control did not expose its endpoint state');
state.zoom = 1.6;
renderControls();
if (!zoomIn.disabled || zoomIn.title !== 'Zoom in (maximum 160%)') throw new Error('Maximum zoom control did not expose its endpoint state');
state.zoom = 1.3;
renderControls();
if (!filterSelect.options.some((option) => option.textContent === `All typologies · ${totalCount}`) || !filterSelect.options.some((option) => option.textContent === `${secondStudy.typology} · ${countBy('typology', secondStudy.typology)}`)) throw new Error('Typology filter did not expose scope-aware counts');
if (!filterEra.options.some((option) => option.textContent === `${uniqueEraStudy.era} · ${countBy('era', uniqueEraStudy.era)}`)) throw new Error('Era filter did not expose study periods and counts');
if (!filterAxis.options.some((option) => option.textContent === `${axisLabel(uniqueAxisStudy.axis)} · ${countBy('axis', uniqueAxisStudy.axis)}`)) throw new Error('Axis filter did not expose geometry axes and counts');
if (filterStatus.options[0].textContent !== `All statuses · ${totalCount}` || filterStatus.options[1].textContent !== `Schematic · ${statusCount('schematic')}` || filterStatus.options[2].textContent !== `Measured · ${statusCount('measured')}`) throw new Error('Status filter did not expose full-collection counts');
state.query = 'gothic';
renderCatalogFilterOptions();
const gothicScopeCount = visibleStudies().length;
if (!filterSelect.options.some((option) => option.textContent === `All typologies · ${gothicScopeCount}`) || !filterSelect.options.some((option) => option.textContent === `Gothic · ${gothicCount}`) || !filterStatus.options.some((option) => option.textContent === `Schematic · ${gothicScopeCount}`)) throw new Error('Catalog filter counts did not follow the active search scope');
state.query = '';
renderCatalogFilterOptions();
context.window.location.href = `https://example.test/atlas/?era=${encodeURIComponent(uniqueEraStudy.era)}#atlas/${firstStudy.id}/plan/exterior/all`;
syncCatalogFromUrl();
if (state.filterEra !== uniqueEraStudy.era || filterEra.value !== uniqueEraStudy.era) throw new Error('Era filter did not restore from the catalog URL');
context.window.location.href = `https://example.test/atlas/?axis=${encodeURIComponent(uniqueAxisStudy.axis)}#atlas/${firstStudy.id}/plan/exterior/all`;
syncCatalogFromUrl();
if (state.filterAxis !== uniqueAxisStudy.axis || filterAxis.value !== uniqueAxisStudy.axis) throw new Error('Axis filter did not restore from the catalog URL');
context.window.location.href = `https://example.test/atlas/?q=central%20plan#atlas/${firstStudy.id}/plan/exterior/all`;
syncCatalogFromUrl();
context.window.location.hash = `#atlas/${firstStudy.id}/plan/exterior/all`;
context.window.location.href = `https://example.test/atlas/?q=%20%20${encodeURIComponent(secondStudy.typology.toUpperCase())}%20%20%20${encodeURIComponent(secondStudy.place.split(',')[0].toUpperCase())}%20%20#atlas/${firstStudy.id}/plan/exterior/all`;
syncCatalogFromUrl();
if (state.query !== multiTermQuery || searchInput.value !== multiTermQuery || !catalogViewRouteUrl().search.includes(`q=${multiTermQuery.replace(/ /g, '+')}`)) throw new Error('Catalog route hydration did not canonicalize repeated query whitespace');
const atlasRoute = parseRoute();
if (atlasRoute.page !== 'atlas' || atlasRoute.contextStudyId !== firstStudy.id) throw new Error('Atlas route parser did not preserve study context');
context.window.location.href = `https://example.test/atlas/?q=central%20plan#method/${secondStudy.id}`;
context.window.location.hash = `#method/${secondStudy.id}`;
const methodRoute = parseRoute();
if (methodRoute.page !== 'method' || methodRoute.contextStudyId !== secondStudy.id) throw new Error('Method route parser did not preserve study context');
if (routeHash('method', true, secondStudy.id) !== `#method/${secondStudy.id}` || routeHash('method', false) !== '#method') throw new Error('Method route hash did not preserve or clear study context');
context.window.location.href = `https://example.test/atlas/?compare=${firstStudy.id}#compare`;
context.window.location.hash = '#compare';
const partialCompareRoute = parseRoute();
if (partialCompareRoute.page !== 'compare' || partialCompareRoute.compareIds.join(',') !== firstStudy.id) throw new Error('Compare route parser did not preserve a partial selection carried in the query');
context.window.location.href = `https://example.test/atlas/#compare/${firstStudy.id}`;
context.window.location.hash = `#compare/${firstStudy.id}`;
const hashPartialCompareRoute = parseRoute();
if (hashPartialCompareRoute.page !== 'compare' || hashPartialCompareRoute.compareIds.join(',') !== firstStudy.id) throw new Error('Compare route parser did not preserve a partial selection carried in the hash');
state.query = '';
state.filterEra = uniqueEraStudy.era;
const eraVisible = visibleStudies();
if (eraVisible.length !== 1 || eraVisible[0].id !== uniqueEraStudy.id) throw new Error('Era filter did not narrow the catalog to the expected study');
state.filterEra = 'all';
state.filterAxis = uniqueAxisStudy.axis;
const axisVisible = visibleStudies();
if (axisVisible.length !== 1 || axisVisible[0].id !== uniqueAxisStudy.id) throw new Error('Axis filter did not narrow the catalog to the expected study');
state.filterAxis = 'all';
state.query = multiTermQuery;
const multiTermVisible = visibleStudies();
if (multiTermVisible.length !== 1 || multiTermVisible[0].id !== secondStudy.id) throw new Error('Multi-term search did not match across study fields');
if (!catalogStatusGuidanceText(multiTermVisible).includes(`Counts for results matching “${multiTermQuery}”: ${statusSummary(multiTermVisible)}.`)) throw new Error('Catalog status guidance did not follow the filtered scope');
state.compareIds = [firstStudy.id, secondStudy.id];
state.activeId = secondStudy.id;
context.window.location.href = `https://example.test/atlas/?q=${multiTermQuery.replace(/ /g, '%20')}&compare=${firstStudy.id}%2C${secondStudy.id}#atlas/${secondStudy.id}/plan/exterior/all`;
updateViewNavigationLinks();
const compareNavLink = navLinks.find((link) => link.dataset.view === 'compare');
const methodNavLink = navLinks.find((link) => link.dataset.view === 'method');
const expectedMethodNavigation = `/atlas/?q=${multiTermQuery.replace(/ /g, '+')}&compare=${firstStudy.id},${secondStudy.id}#method/${secondStudy.id}`;
if (methodNavigationUrl() !== expectedMethodNavigation || methodNavLink.href !== methodNavigationUrl() || methodLink.href !== methodNavigationUrl()) throw new Error(`Method links did not preserve the active study, catalog scope, and comparison selection: ${methodNavigationUrl()} / ${methodNavLink.href} / ${methodLink.href}`);
const expectedComparisonNavigation = `/atlas/?q=${multiTermQuery.replace(/ /g, '+')}#compare/${firstStudy.id},${secondStudy.id}`;
if (comparisonNavigationUrl() !== expectedComparisonNavigation || viewNavigationUrl('compare') !== comparisonNavigationUrl() || compareNavLink.href !== comparisonNavigationUrl()) throw new Error(`Compare links did not preserve the focused selection: ${comparisonNavigationUrl()} / ${compareNavLink.href}`);
state.compareIds = [firstStudy.id];
const expectedPartialComparisonNavigation = `/atlas/?q=${multiTermQuery.replace(/ /g, '+')}&compare=${firstStudy.id}#compare`;
if (comparisonNavigationUrl() !== expectedPartialComparisonNavigation || viewNavigationUrl('compare') !== comparisonNavigationUrl()) throw new Error(`Compare links did not preserve a partial selection: ${comparisonNavigationUrl()}`);
state.compareIds = [firstStudy.id, secondStudy.id];
const contextualAtlasHref = viewNavigationUrl('atlas');
const expectedContextualAtlasHref = `/atlas/?q=${multiTermQuery.replace(/ /g, '+')}&compare=${firstStudy.id},${secondStudy.id}#atlas`;
if (contextualAtlasHref !== expectedContextualAtlasHref || navLinks.find((link) => link.dataset.view === 'atlas').href !== contextualAtlasHref) throw new Error(`Atlas link did not preserve the catalog scope: ${contextualAtlasHref}`);
context.window.location.href = `https://example.test/atlas/?q=central%20plan#atlas/${firstStudy.id}/plan/exterior/all`;
const stateAwareStudyHref = atlasStudyNavigationUrl(secondStudy.id);
const stateAwareCatalogHref = catalogViewRouteUrl();
if (!stateAwareStudyHref.includes(`q=${multiTermQuery.replace(/ /g, '+')}`) || !stateAwareStudyHref.includes(`compare=${firstStudy.id},${secondStudy.id}`) || !stateAwareCatalogHref.href.includes(`q=${multiTermQuery.replace(/ /g, '+')}`) || !stateAwareCatalogHref.href.includes(`compare=${firstStudy.id},${secondStudy.id}`)) throw new Error(`Route links did not use current catalog state: ${stateAwareStudyHref} / ${stateAwareCatalogHref.href}`);
state.compareIds = [];
const highlighted = highlightSearchText('Gothic · Chartres, France');
if (!highlighted.includes('<mark class="search-hit">Gothic</mark>') || !highlighted.includes('<mark class="search-hit">Chartres</mark>')) throw new Error('Catalog search did not highlight matching terms');
const escapedHighlight = highlightSearchText('Gothic <study>');
if (escapedHighlight.includes('<study>') || !escapedHighlight.includes('&lt;study&gt;')) throw new Error('Catalog search highlighting did not escape dynamic text');
state.query = 'c++';
if (!highlightSearchText('C++ module').includes('<mark class="search-hit">C++</mark>')) throw new Error('Catalog search highlighting did not escape regex punctuation');
state.query = 'section ratio';
if (searchMatchContext(context.window.CHURCH_GEOMETRY[0]) !== 'Found in derived ratios') throw new Error('Catalog search did not explain a hidden derived-ratio match');
if (!catalogStudyAriaLabel(context.window.CHURCH_GEOMETRY[0], false).includes('Found in derived ratios')) throw new Error('Catalog accessibility label did not preserve hidden match context');
state.query = 'apollinare';
if (searchMatchContext(context.window.CHURCH_GEOMETRY[0]) !== 'Found in reference') throw new Error('Catalog search did not explain a hidden reference match');
state.query = 'illustrative proportions';
if (visibleStudies().length !== schematicCount || searchMatchContext(context.window.CHURCH_GEOMETRY[0]) !== 'Found in provenance' || !catalogStudyAriaLabel(context.window.CHURCH_GEOMETRY[0], false).includes('Found in provenance')) throw new Error('Catalog search did not index schema-backed provenance definitions or explain the hidden match');
state.query = 'radiality';
if (!studySearchText(context.window.CHURCH_GEOMETRY[0]).includes('reading profile radiality 48') || searchMatchContext(context.window.CHURCH_GEOMETRY[0]) !== 'Found in reading profile' || !catalogStudyAriaLabel(context.window.CHURCH_GEOMETRY[0], false).includes('Found in reading profile')) throw new Error('Catalog search did not index reading-profile scores or explain their hidden match context');
state.query = '01';
if (!visibleStudies().some((study) => study.id === firstStudy.id) || !studySearchText(firstStudy).includes(firstStudy.index) || !searchMatchContext(firstStudy).includes('Found in study index') || !catalogStudyAriaLabel(firstStudy, false).includes('Found in study index') || !highlightSearchText(firstStudy.index).includes(`<mark class="search-hit">${firstStudy.index}</mark>`)) throw new Error('Catalog search did not index, explain, and highlight the curated study index');
state.query = '';
let navPrevented = false;
handleViewNavigation({ currentTarget: { dataset: { view: 'compare' } }, button: 1, metaKey: false, ctrlKey: false, shiftKey: false, altKey: false, preventDefault() { navPrevented = true; } });
if (navPrevented) throw new Error('Modified navigation clicks must preserve native view links');
navPrevented = false;
handleViewNavigation({ currentTarget: { dataset: { view: 'compare' } }, button: 0, metaKey: true, ctrlKey: false, shiftKey: false, altKey: false, preventDefault() { navPrevented = true; } });
if (navPrevented) throw new Error('Command-click navigation must preserve native view links');
let prevented = false;
state.page = 'atlas';
state.compareIds = [firstStudy.id];
handleKeyboard({ key: 'c', target: { tagName: 'body', isContentEditable: false }, metaKey: false, ctrlKey: false, altKey: false, preventDefault() { prevented = true; } });
if (!prevented || keyboardStatus.textContent !== 'Select one more study to open comparison.') throw new Error('Comparison shortcut must give a singular next step for a partial selection');
prevented = false;
state.compareIds = [];
handleKeyboard({ key: 'c', target: { tagName: 'body', isContentEditable: false }, metaKey: false, ctrlKey: false, altKey: false, preventDefault() { prevented = true; } });
if (!prevented || keyboardStatus.textContent !== 'Select at least two studies to open comparison.') throw new Error('Comparison shortcut must explain when more selection is needed');
prevented = false;
handleKeyboard({ key: 'c', target: { tagName: 'button', isContentEditable: false, getAttribute(name) { return name === 'aria-keyshortcuts' ? 'c' : ''; } }, metaKey: false, ctrlKey: false, altKey: false, preventDefault() { prevented = true; } });
if (!prevented || keyboardStatus.textContent !== 'Select at least two studies to open comparison.') throw new Error('A matching shortcut control did not preserve its Atlas shortcut');
prevented = false;
const unrelatedButtonStatus = keyboardStatus.textContent;
handleKeyboard({ key: 'c', target: { tagName: 'button', isContentEditable: false, getAttribute() { return ''; } }, metaKey: false, ctrlKey: false, altKey: false, preventDefault() { prevented = true; } });
if (prevented || keyboardStatus.textContent !== unrelatedButtonStatus) throw new Error('An unrelated button hijacked a global Atlas shortcut');
if (zoomDeltaForKey('+') !== 0.15 || zoomDeltaForKey('-') !== -0.15 || zoomDeltaForKey('x') !== 0) throw new Error('Drawing zoom keyboard mapping did not expose plus/minus increments only');
state.mode = 'section';
state.surface = 'interior';
state.layer = 'axis';
state.zoom = 1.3;
state.query = 'central plan';
state.compareIds = [firstStudy.id, secondStudy.id];
const hash = routeHash('atlas', true, secondStudy.id);
const href = navigationUrl(hash);
const expectedStudyHash = `#atlas/${secondStudy.id}/section/interior/axis/1.3`;
if (hash !== expectedStudyHash) throw new Error(`Unexpected study route: ${hash}`);
if (href !== `/atlas/?q=central%20plan${expectedStudyHash}`) throw new Error(`Catalog scope was not preserved: ${href}`);
const comparisonHref = atlasStudyNavigationUrl(secondStudy.id);
if (comparisonHref !== `/atlas/?q=central+plan&compare=${firstStudy.id},${secondStudy.id}${expectedStudyHash}`) throw new Error(`Focused comparison context was not preserved: ${comparisonHref}`);
const printRoute = studyRoutePath(secondStudy.id);
if (printRoute !== `/atlas/${expectedStudyHash}` || studyRouteUrl(secondStudy.id).searchParams.has('q')) throw new Error(`Reproducible study route did not clear catalog scope: ${printRoute}`);
const navigation = { setAttribute(name, value) { this[name] = value; } };
const position = { textContent: '' };
const previous = { disabled: false, setAttribute(name, value) { this[name] = value; }, title: '' };
const next = { disabled: false, setAttribute(name, value) { this[name] = value; }, title: '' };
elements.set('#studyNav', navigation);
elements.set('#studyNavPosition', position);
elements.set('#prevStudy', previous);
elements.set('#nextStudy', next);
state.query = '';
state.activeId = firstStudy.id;
renderStudyNav();
if (position.textContent !== `01 / ${studyCountLabel} visible` || navigation['aria-label'] !== `Move between studies; showing study 1 of ${studyCount} visible studies` || previous['aria-label'] !== `Previous study: ${studyIdentity(lastStudy)}` || next['aria-label'] !== `Next study: ${studyIdentity(secondStudy)}` || previous.title !== `Previous: ${studyIdentity(lastStudy)}` || next.title !== `Next: ${studyIdentity(secondStudy)}` || previous.disabled || next.disabled) throw new Error('Full study navigation position and indexed destinations did not render');
state.query = 'gothic';
state.activeId = secondStudy.id;
const gothicSearchCount = visibleStudies().length;
renderStudyNav();
if (position.textContent !== `01 / ${String(gothicSearchCount).padStart(2, '0')} visible` || navigation['aria-label'] !== `Move between studies; showing study 1 of ${gothicSearchCount} visible studies` || previous.disabled || next.disabled) throw new Error('Filtered study navigation position did not render');
state.activeId = firstStudy.id;
renderStudyNav();
if (position.textContent !== `Outside / ${String(gothicSearchCount).padStart(2, '0')} visible` || navigation['aria-label'] !== `Move between studies; current study is outside the ${gothicSearchCount} visible studies` || previous.disabled || next.disabled) throw new Error('Out-of-scope study navigation did not expose its visible recovery target');
state.query = '';
state.activeId = firstStudy.id;
const searchText = studySearchText(context.window.CHURCH_GEOMETRY[0]);
if (!searchText.includes('section ratio 0.60') || !searchText.includes('module / span 0.27') || !searchText.includes('radial reach 15.0 m')) throw new Error('Catalog search did not index derived readings');
const specialCharacterStudy = { ...context.window.CHURCH_GEOMETRY[0], emphasis: 'Light & <line>' };
const elevation = drawElevation(specialCharacterStudy);
if (!elevation.includes('light &amp; &lt;line&gt;') || elevation.includes('Light & <line>')) throw new Error('Dynamic SVG labels must escape study text');
const originalUnitSymbol = context.window.CHURCH_GEOMETRY_SCHEMA.unitSymbol;
context.window.CHURCH_GEOMETRY_SCHEMA.unitSymbol = '<unit>';
const planWithUnsafeUnit = drawPlan(context.window.CHURCH_GEOMETRY[0]);
const sectionWithUnsafeUnit = drawSection(context.window.CHURCH_GEOMETRY[0]);
context.window.CHURCH_GEOMETRY_SCHEMA.unitSymbol = originalUnitSymbol;
if (!planWithUnsafeUnit.includes('&lt;unit&gt;') || planWithUnsafeUnit.includes('<unit>') || !sectionWithUnsafeUnit.includes('&lt;unit&gt;') || sectionWithUnsafeUnit.includes('<unit>')) throw new Error('Schema unit symbols must be escaped in generated SVG labels');
console.log('Route-native catalog link smoke test passed.');
NODE
